IBX-5888: Verification of whether the given landingPage field value is correct has been changed
ezsystems/ezplatform-automated-translation pull request #29
Opened 2023-06-30 08:35 UTC by mateuszdebinski

Jira: https://issues.ibexa.co/browse/IBX-5888.

for tests to pass to CI (if they are connected), we need to add a dependency for landing page field type on the fly

2023-07-20 06:26 UTC, webhdx requested changes

2023-07-20 06:26 UTC, webhdx commented on tests/lib/Encoder/Field/PageBuilderFieldEncoderTest.php
> +            ->getMock();
If you want to write fewer lines you can do:

```suggestion
        $blockAttributeEncoderManagerMock = $this->createMock(BlockAttributeEncoderManager::class);
```

2023-07-20 06:26 UTC, webhdx commented on tests/lib/Encoder/Field/PageBuilderFieldEncoderTest.php
> +            ->expects(self::atLeastOnce())
You probably don't care if this method was called or not as long as you get correct return value. It only makes tests more rigid and prone to breaking after code refactoring.

2023-07-20 06:26 UTC, webhdx commented on tests/lib/Encoder/Field/PageBuilderFieldEncoderTest.php
> +        self::assertTrue($subject->canEncode($field));
For me it looks like this test should be split into 2 tests, one covering `canEncode` and the other `encode` method. The smaller unit test the better.

2023-07-20 06:26 UTC, webhdx commented on tests/lib/Encoder/Field/PageBuilderFieldEncoderTest.php
> +        self::assertEquals($this->getEncodeResult(), trim($result));
Nitpick: I'm not a fan of transforming actual output to confirm it matches expected value. It should be the other way around - compare raw value with what you expect to see.

2023-07-20 06:26 UTC, webhdx commented on tests/lib/Encoder/Field/PageBuilderFieldEncoderTest.php
> +    public function testDecode(): void
Same remarks from `testEncode` apply here.

2023-07-20 06:26 UTC, webhdx commented on tests/lib/Encoder/Field/PageBuilderFieldEncoderTest.php
> +        $proxyManager = new ProxyGenerator('var/cache/repository/proxy');
Do you really need to provide proxy for the object? It should work without that. Encoder is expecting `Value` class and it doesn't do anything in particular on `ProxyGenerator` object.

2023-07-20 08:18 UTC, mateuszdebinski commented on tests/lib/Encoder/Field/PageBuilderFieldEncoderTest.php
> +        $proxyManager = new ProxyGenerator('var/cache/repository/proxy');
yes we need it because in `canDecode` we have: `return class_exists(Value::class) && is_subclass_of($type, Value::class);`
this `is_subclass_of($type, Value::class);` not working with LandingPage\Value

2023-07-28 06:57 UTC, konradoboza commented on tests/lib/Encoder/Field/PageBuilderFieldEncoderTest.php
> +class PageBuilderFieldEncoderTest extends TestCase
```suggestion
final class PageBuilderFieldEncoderTest extends TestCase
```

2023-07-28 06:57 UTC, konradoboza commented on tests/lib/Encoder/Field/PageBuilderFieldEncoderTest.php
> +        parent::setUp();
Is this needed?

2023-07-28 07:17 UTC, mateuszdebinski commented on tests/lib/Encoder/Field/PageBuilderFieldEncoderTest.php
> +        parent::setUp();
no, not needed, removed in the latest commit

2023-07-28 07:19 UTC, konradoboza approved these changes

2023-07-31 06:18 UTC, webhdx commented on tests/lib/Encoder/Field/PageBuilderFieldEncoderTest.php
> +        $proxyManager = new ProxyGenerator('var/cache/repository/proxy');
It doesn't make any sense. You are proxying `EzSystems\EzPlatformPageFieldType\FieldType\LandingPage\Value` class. `canDecode` is incorrectly implemented. Replace `is_subclass_of` with `is_a` and you won't need to proxy any objects in tests.

2023-07-31 06:18 UTC, webhdx requested changes
Please see my other comment. There seems to be a bug in `PageBuilderFieldEncoder::canDecode`.

2023-07-31 07:29 UTC, webhdx approved these changes

2023-07-31 09:41 UTC, kisztof approved these changes

2023-08-01 08:19 UTC, mnocon approved these changes
- Tested with `ezstring` and `ezrichtext` fields ✅ 
- Tested with `code` and `text` Page Builder blocks ✅ 

QA Approved!

2023-08-01 09:54 UTC, merged